### ISSUE TITLE
btc import

### ISSUE THREAD

**Issue by fugw110** [elevenyellow/coinfy#4]
btc import  have two format  by private key, 'regular' and 'segwit' .
but btc export have not this two format, so when I import wallet by private key ,which format will I select?
thank you!

**Comment by Josema** [comment]
With the same private key you can generate a regular address or a segwit address. So when exporting you will always get the same private key in both cases.

**Comment by fugw110** [comment]
thank you for your reply.
But as a user, after I exported my wallet, I didn't know which format to import on coinfy. 
Because I chose regular or segwit to import addresses that are different.

**Comment by Josema** [comment]
Yes, I agree that is confusing.

**Comment by fugw110** [comment]
What I want to talk about is how to tell users to choose the right one as a developer when importing. 
According to my current test, on testnet ,the address importing at the beginning of  'm' needs to be successful by using 'regular'. The address importing at the beginning of '2' requires' segwit '. 
so How should I deal with it ?
thank you

**Comment by Josema** [comment]
If you create a new asset by default is segwit. You don't have to deal with private keys, you have to deal with the seed generate by coinfy.

If your case is that you have a private key from another wallet/app instead of the 12 words then you need to know what address you were using.

Sorry but don't know where is the issue here. Explain me a real case. Where did you get that private key?

**Comment by fugw110** [comment]
My private key was exported in my wallet export tab on coinfy, and no format was prompted when I exported it. 
In the past, I created the address at the beginning of 'm', which can not be imported by 'segwit'.

**Comment by fugw110** [comment]
ok thank you !
